package models

import (
	"time"
)

// OpportunityType represents the category of opportunity identified
type OpportunityType string

const (
	OpportunityTypeContentGap          OpportunityType = "content_gap"
	OpportunityTypeContentFreshness    OpportunityType = "content_freshness"
	OpportunityTypeRedditParticipation OpportunityType = "reddit_participation"
	OpportunityTypeReviewSites         OpportunityType = "review_sites"
	OpportunityTypeCaseStudy           OpportunityType = "case_study"
	OpportunityTypeSEOImprovement      OpportunityType = "seo_improvement"
	OpportunityTypePROpportunity       OpportunityType = "pr_opportunity"
	OpportunityTypeLinkedInPresence    OpportunityType = "linkedin_presence"
	OpportunityTypeComparisonContent   OpportunityType = "comparison_content"
	OpportunityTypeCitationSource      OpportunityType = "citation_source"
	OpportunityTypeFAQContent          OpportunityType = "faq_content"
	OpportunityTypeCompetitorResponse  OpportunityType = "competitor_response"
	OpportunityTypeIntegrationContent  OpportunityType = "integration_content"
	OpportunityTypeOther               OpportunityType = "other"
)

// OpportunityStatus represents the current state of an opportunity
type OpportunityStatus string

const (
	OpportunityStatusOpen       OpportunityStatus = "open"
	OpportunityStatusInProgress OpportunityStatus = "in_progress"
	OpportunityStatusCompleted  OpportunityStatus = "completed"
	OpportunityStatusDismissed  OpportunityStatus = "dismissed" // suppressed/archived
)

// Opportunity represents a gap or improvement area identified from AI response analysis
type Opportunity struct {
	ID         string            `json:"id" bson:"_id"`
	OrgID      string            `json:"orgId" bson:"org_id"`
	BrandID    string            `json:"brandId" bson:"brand_id"`
	PromptID   string            `json:"promptId" bson:"prompt_id"`
	ResponseID string            `json:"responseId" bson:"response_id"`
	LLMID      string            `json:"llmId,omitempty" bson:"llm_id,omitempty"` // LLM ID used for analysis (for action generation)
	Type       OpportunityType   `json:"type" bson:"type"`
	Status     OpportunityStatus `json:"status" bson:"status"`

	// Core opportunity details
	Title       string `json:"title" bson:"title"`             // Short, actionable title
	Description string `json:"description" bson:"description"` // Detailed description of what to do

	// Context and evidence
	CurrentState   string `json:"currentState" bson:"current_state"`     // What the brand currently has/lacks
	SourceEvidence string `json:"sourceEvidence" bson:"source_evidence"` // Specific sources/citations that show the gap

	// Priority and scoring
	ImpactScore    int    `json:"impactScore" bson:"impact_score"`       // 1-100, LLM assigned
	Urgency        string `json:"urgency" bson:"urgency"`                // "high", "medium", "low" - time sensitivity
	EffortEstimate string `json:"effortEstimate" bson:"effort_estimate"` // "low", "medium", "high" - rough effort

	// Internal fields
	ContentHash string                 `json:"contentHash" bson:"content_hash"` // For deduplication
	ActionID    string                 `json:"actionId,omitempty" bson:"action_id,omitempty"`
	IsArchived  bool                   `json:"isArchived" bson:"is_archived"`                // True when suppressed
	Metadata    map[string]interface{} `json:"metadata,omitempty" bson:"metadata,omitempty"` // Additional flexible data
	CreatedAt   time.Time              `json:"createdAt" bson:"created_at"`
	UpdatedAt   time.Time              `json:"updatedAt" bson:"updated_at"`
}

// ActionStatus represents the current state of an action
type ActionStatus string

const (
	ActionStatusPreparing  ActionStatus = "preparing"   // Action is being generated by AI
	ActionStatusReady      ActionStatus = "ready"       // Action is ready (prepared); execution can start
	ActionStatusFailed     ActionStatus = "failed"      // Preparation failed (LLM/parse error)
	ActionStatusPending    ActionStatus = "pending"     // Action is pending execution
	ActionStatusInProgress ActionStatus = "in_progress" // Action is in progress
	ActionStatusCompleted  ActionStatus = "completed"   // Action is completed
)

// ActionType represents the type of action
type ActionType string

const (
	// Creating net-new content (blogs, pages, comparisons, FAQs, docs)
	ActionTypeContentCreation ActionType = "CONTENT_CREATION"

	// Updating, refreshing, or restructuring existing content
	ActionTypeContentUpdate ActionType = "CONTENT_UPDATE"

	// Technical changes to make content crawlable, renderable, or indexable by AI/search
	ActionTypeSEO ActionType = "SEO"

	// Structured data, schemas, metadata, and machine-readable signals
	ActionTypeStructuredData ActionType = "STRUCTURED_DATA"

	// External distribution on platforms (Reddit, LinkedIn, Quora, X, etc.)
	ActionTypeSocial ActionType = "SOCIAL"

	// Reviews, citations, mentions, analyst reports, directories
	ActionTypePR ActionType = "PR"

	// Integration pages, partnership docs, API pages
	ActionTypeIntegration ActionType = "INTEGRATION"

	// Competitive positioning responses (comparisons, rebuttals, alternative pages)
	ActionTypeCompetitive ActionType = "COMPETITIVE"

	// Trust-building assets (case studies, testimonials, proof pages)
	ActionTypeTrust ActionType = "TRUST"

	// Monitoring, verification, and checks (AI crawl checks, visibility audits)
	ActionTypeVerification ActionType = "VERIFICATION"

	// Catch-all for rare or experimental actions
	ActionTypeOther ActionType = "OTHER"
)

// ExecutionMode represents how the action should be executed
type ExecutionMode string

const (
	ExecutionModeManualCopy ExecutionMode = "manual_copy" // User manually copies content
	ExecutionModeAPI        ExecutionMode = "api"         // Automated via API
	ExecutionModeManual     ExecutionMode = "manual"      // Manual execution
)

// ActionAsset represents an asset associated with an action
type ActionAsset struct {
	AssetType string      `json:"asset_type" bson:"asset_type"` // "text", "checklist", "image", etc.
	Role      string      `json:"role" bson:"role"`             // "blog_draft", "on_page_seo", etc.
	Title     string      `json:"title" bson:"title"`
	Content   interface{} `json:"content" bson:"content"` // Can be string or array depending on asset_type
}

// ActionStep represents a single step in an action plan
type ActionStep struct {
	Order       int    `json:"order" bson:"order"`
	Title       string `json:"title" bson:"title"`
	Instruction string `json:"instruction" bson:"instruction"` // Detailed instruction for the step
	Completed   bool   `json:"completed,omitempty" bson:"completed,omitempty"`
}

// Action represents a detailed action plan generated from an opportunity
type Action struct {
	ID            string `json:"action_id" bson:"_id"` // Using action_id for API response
	OrgID         string `json:"orgId,omitempty" bson:"org_id,omitempty"`
	OpportunityID string `json:"opportunity_id" bson:"opportunity_id"`
	BrandID       string `json:"brandId,omitempty" bson:"brand_id,omitempty"`

	// Action classification
	ActionType    ActionType    `json:"action_type" bson:"action_type"`
	ExecutionMode ExecutionMode `json:"execution_mode" bson:"execution_mode"`

	// Core action details
	Title   string `json:"title" bson:"title"`
	Summary string `json:"summary" bson:"summary"` // Brief summary of the action

	// Priority and impact
	Priority       string `json:"priority" bson:"priority"`               // "high", "medium", "low"
	Effort         string `json:"effort" bson:"effort"`                   // "low", "medium", "high"
	ExpectedImpact string `json:"expected_impact" bson:"expected_impact"` // "high", "medium", "low"

	// Action content
	Assets          []ActionAsset `json:"assets" bson:"assets"`                     // Assets like blog drafts, checklists, etc.
	Steps           []ActionStep  `json:"steps" bson:"steps"`                       // Execution steps
	SuccessCriteria []string      `json:"success_criteria" bson:"success_criteria"` // Criteria for success

	// Legacy fields (kept for backward compatibility)
	Description     string   `json:"description,omitempty" bson:"description,omitempty"`
	EstimatedEffort string   `json:"estimatedEffort,omitempty" bson:"estimated_effort,omitempty"` // "low", "medium", "high"
	Resources       []string `json:"resources,omitempty" bson:"resources,omitempty"`

	// Assignment
	Assignee string `json:"assignee,omitempty" bson:"assignee,omitempty"` // User ID or email of the person assigned to this action

	// Status
	Status    ActionStatus `json:"status" bson:"status"`
	CreatedAt time.Time    `json:"createdAt,omitempty" bson:"created_at,omitempty"`
	UpdatedAt time.Time    `json:"updatedAt,omitempty" bson:"updated_at,omitempty"`
}

// LLMOpportunity represents the opportunity structure returned by LLM
type LLMOpportunity struct {
	Type        string `json:"type"`
	Title       string `json:"title"`
	Description string `json:"description"`

	// Context and evidence
	CurrentState   string `json:"current_state"`   // What brand currently has/lacks
	SourceEvidence string `json:"source_evidence"` // Specific evidence from sources

	// Priority
	ImpactScore    int    `json:"impact_score"`    // 1-100
	Urgency        string `json:"urgency"`         // high, medium, low
	EffortEstimate string `json:"effort_estimate"` // low, medium, high

	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

// LLMActionPlan represents the action plan structure returned by LLM
type LLMActionPlan struct {
	ActionType      string           `json:"action_type"`    // "CONTENT_CREATION", "SEO", etc.
	ExecutionMode   string           `json:"execution_mode"` // "manual_copy", "api", "manual"
	Title           string           `json:"title"`
	Summary         string           `json:"summary"`
	Priority        string           `json:"priority"`        // "high", "medium", "low"
	Effort          string           `json:"effort"`          // "low", "medium", "high"
	ExpectedImpact  string           `json:"expected_impact"` // "high", "medium", "low"
	Assets          []LLMActionAsset `json:"assets"`
	Steps           []LLMActionStep  `json:"steps"`
	SuccessCriteria []string         `json:"success_criteria"`
	// Legacy fields
	Description     string   `json:"description,omitempty"`
	EstimatedEffort string   `json:"estimated_effort,omitempty"`
	Resources       []string `json:"resources,omitempty"`
}

// LLMActionAsset represents an asset from LLM response
type LLMActionAsset struct {
	AssetType string      `json:"asset_type"` // "text", "checklist", "image", etc.
	Role      string      `json:"role"`       // "blog_draft", "on_page_seo", etc.
	Title     string      `json:"title"`
	Content   interface{} `json:"content"` // Can be string or array
}

// LLMActionStep represents an action step from LLM response
type LLMActionStep struct {
	Order       int    `json:"order"`
	Title       string `json:"title"`
	Instruction string `json:"instruction"` // Detailed instruction
}

// ValidOpportunityTypes returns all valid opportunity types
func ValidOpportunityTypes() []OpportunityType {
	return []OpportunityType{
		OpportunityTypeContentGap,
		OpportunityTypeContentFreshness,
		OpportunityTypeRedditParticipation,
		OpportunityTypeReviewSites,
		OpportunityTypeCaseStudy,
		OpportunityTypeSEOImprovement,
		OpportunityTypePROpportunity,
		OpportunityTypeLinkedInPresence,
		OpportunityTypeComparisonContent,
		OpportunityTypeCitationSource,
		OpportunityTypeFAQContent,
		OpportunityTypeCompetitorResponse,
		OpportunityTypeIntegrationContent,
		OpportunityTypeOther,
	}
}

// IsValidOpportunityType checks if the given type is valid
func IsValidOpportunityType(t string) bool {
	for _, valid := range ValidOpportunityTypes() {
		if string(valid) == t {
			return true
		}
	}
	return false
}

// ParseOpportunityType converts a string to OpportunityType with fallback
func ParseOpportunityType(t string) OpportunityType {
	if IsValidOpportunityType(t) {
		return OpportunityType(t)
	}
	return OpportunityTypeOther
}
